### ISSUE TITLE
[Bug]: I am getting a lot of ticking entities from this mod, it may be related to an issue in my world where chunks stop loading

### ISSUE THREAD

**Issue by lSherozl** [bonsaistudi0s/EndermanOverhaul#38]
### Bug Description

This is the only part of the log that's relevant, but as you can see that bottom message of skipping entity ID spams for much longer than I have shown, if I directly teleport to this location it causes chunks to not load, if I travel there, it gives the below log with a very long log spam before chunks load. I think the enderman may be the culprit. 

[23:39:45] [Server thread/WARN]: Neruina Caught Exception
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.entity.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:68) ~[NoSeeNoTick-2.0.0-1.19.2.jar%23950!/:2.0.0-build.9999]
	at net.minecraft.entity.TickOptimizer.entityTicking(TickOptimizer.java:25) ~[NoSeeNoTick-2.0.0-1.19.2.jar%23950!/:2.0.0-build.9999]
	at net.minecraft.world.level.Level.mixinextras$bridge$entityTicking$158(Level.java) ~[client-1.19.2-20220805.130853-srg.jar%231118!/:?]
	at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:131) ~[neruina-1.3.0-forge+1.18.2-1.20.1.jar%23938!/:?]
	at net.minecraft.world.level.Level.wrapOperation$fik000$catchTickingEntities(Level.java:7542) ~[client-1.19.2-20220805.130853-srg.jar%231118!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:3039) ~[client-1.19.2-20220805.130853-srg.jar%231118!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[client-1.19.2-20220805.130853-srg.jar%231118!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.2-20220805.130853-srg.jar%231118!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[client-1.19.2-20220805.130853-srg.jar%231118!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%231118!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%231118!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%231118!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%231118!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%231118!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraftforge.common.util.LazyOptional.ifPresent(net.minecraftforge.common.util.NonNullConsumer)" because the return value of "net.minecraft.world.entity.LivingEntity.getLeashStateCache()" is null
	at net.minecraft.world.entity.LivingEntity.handler$fpn00a$onTick(LivingEntity.java:27616) ~[client-1.19.2-20220805.130853-srg.jar%231118!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2371) ~[client-1.19.2-20220805.130853-srg.jar%231118!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:318) ~[client-1.19.2-20220805.130853-srg.jar%231118!/:?]
	at tech.alexnijjar.endermanoverhaul.common.entities.base.BaseEnderman.m_8119_(BaseEnderman.java:197) ~[endermanoverhaul-forge-1.19.2-0.0.1.jar%23794!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[client-1.19.2-20220805.130853-srg.jar%231118!/:?]
	at net.minecraft.entity.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:62) ~[NoSeeNoTick-2.0.0-1.19.2.jar%23950!/:2.0.0-build.9999]
	... 14 more
[23:39:45] [Render thread/INFO]: [CHAT] [Neruina]: Caught Ticking Entity [Dark Oak Enderman] at position [x=9527.0, y=40.0, z=9446.0]. It has been killed.
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id minecraft:
[23:39:46] [Render thread/WARN]: Skipping Entity with id Minecraft:

This Goes on for much longer, at least hundred plus lines of this

### How to Reproduce?

You cant reporduce this issue, its on a specific modpack with a specific world, What I do know is neurina often catches ticking enderman. You can get Neurina or other mods which will show u which endermans become ticking entities 

### Version

0.0.1

### Mod Loader Version

1.19.2 43.3.5

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by lSherozl** [comment]
After some testing its not this mod causing chunk issues HOWEVER, there are a lot of ticking enderman here and there

**Comment by lSherozl** [comment]
Also got this error, not sure what it means but is also something that did crash my game at one point, maybe I screwed up a datapack or the datapack is on an older version [01:23:51] [Render thread/ERROR]: Exception when calling the full entity renderer before rendering the icon. minecraft:enderman
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
	at software.bernie.geckolib3.core.event.predicate.AnimationEvent.getExtraDataOfType(AnimationEvent.java:75) ~[geckolib-forge-1.19-3.1.40.jar%23843!/:3.1.40]
	at tech.alexnijjar.endermanoverhaul.common.entities.ReplacedEnderman.getEndermanFromState(ReplacedEnderman.java:69) ~[endermanoverhaul-forge-1.19.2-0.0.1.jar%23790!/:?]
	at tech.alexnijjar.endermanoverhaul.common.entities.ReplacedEnderman.lambda$registerControllers$2(ReplacedEnderman.java:46) ~[endermanoverhaul-forge-1.19.2-0.0.1.jar%23790!/:?]
	at software.bernie.geckolib3.core.controller.AnimationController.testAnimationPredicate(AnimationController.java:542) ~[geckolib-forge-1.19-3.1.40.jar%23843!/:3.1.40]
	at software.bernie.geckolib3.core.controller.AnimationController.process(AnimationController.java:409) ~[geckolib-forge-1.19-3.1.40.jar%23843!/:3.1.40]
	at software.bernie.geckolib3.core.processor.AnimationProcessor.tickAnimation(AnimationProcessor.java:69) ~[geckolib-forge-1.19-3.1.40.jar%23843!/:3.1.40]
	at software.bernie.geckolib3.model.AnimatedGeoModel.setCustomAnimations(AnimatedGeoModel.java:90) ~[geckolib-forge-1.19-3.1.40.jar%23843!/:3.1.40]
	at tech.alexnijjar.endermanoverhaul.client.renderer.base.BaseEndermanModel.setCustomAnimations(BaseEndermanModel.java:39) ~[endermanoverhaul-forge-1.19.2-0.0.1.jar%23790!/:?]
	at tech.alexnijjar.endermanoverhaul.client.renderer.base.ReplacedEndermanModel.setCustomAnimations(ReplacedEndermanModel.java:35) ~[endermanoverhaul-forge-1.19.2-0.0.1.jar%23790!/:?]
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:53) ~[geckolib-forge-1.19-3.1.40.jar%23843!/:3.1.40]
	at software.bernie.geckolib3.renderers.geo.GeoReplacedEntityRenderer.render(GeoReplacedEntityRenderer.java:198) ~[geckolib-forge-1.19-3.1.40.jar%23843!/:3.1.40]
	at software.bernie.geckolib3.renderers.geo.GeoReplacedEntityRenderer.m_7392_(GeoReplacedEntityRenderer.java:123) ~[geckolib-forge-1.19-3.1.40.jar%23843!/:3.1.40]
	at xaero.common.minimap.render.radar.EntityIconPrerenderer.prerender(EntityIconPrerenderer.java:306) ~[Xaeros_Minimap_23.9.7_Forge_1.19.1.jar%231100!/:23.9.7]
	at xaero.common.minimap.render.radar.EntityIconManager.getEntityHeadTexture(EntityIconManager.java:139) ~[Xaeros_Minimap_23.9.7_Forge_1.19.1.jar%231100!/:23.9.7]
	at xaero.common.minimap.render.radar.element.RadarRenderer.renderElement(RadarRenderer.java:111) ~[Xaeros_Minimap_23.9.7_Forge_1.19.1.jar%231100!/:23.9.7]
	at xaero.common.minimap.render.radar.element.RadarRenderer.renderElement(RadarRenderer.java:34) ~[Xaeros_Minimap_23.9.7_Forge_1.19.1.jar%231100!/:23.9.7]
	at xaero.common.minimap.element.render.map.MinimapElementMapRendererHandler.transformAndRenderForRenderer(MinimapElementMapRendererHandler.java:59) ~[Xaeros_Minimap_23.9.7_Forge_1.19.1.jar%231100!/:23.9.7]
	at xaero.common.minimap.element.render.MinimapElementRendererHandler.renderForRenderer(MinimapElementRendererHandler.java:66) ~[Xaeros_Minimap_23.9.7_Forge_1.19.1.jar%231100!/:23.9.7]
	at xaero.common.minimap.element.render.MinimapElementRendererHandler.render(MinimapElementRendererHandler.java:41) ~[Xaeros_Minimap_23.9.7_Forge_1.19.1.jar%231100!/:23.9.7]
	at xaero.common.minimap.element.render.map.MinimapElementMapRendererHandler.render(MinimapElementMapRendererHandler.java:35) ~[Xaeros_Minimap_23.9.7_Forge_1.19.1.jar%231100!/:23.9.7]
	at xaero.common.minimap.render.MinimapFBORenderer.renderChunksToFBO(MinimapFBORenderer.java:320) ~[Xaeros_Minimap_23.9.7_Forge_1.19.1.jar%231100!/:23.9.7]
	at xaero.common.minimap.render.MinimapFBORenderer.renderChunks(MinimapFBORenderer.java:93) ~[Xaeros_Minimap_23.9.7_Forge_1.19.1.jar%231100!/:23.9.7]
	at xaero.common.minimap.render.MinimapRenderer.renderMinimap(MinimapRenderer.java:148) ~[Xaeros_Minimap_23.9.7_Forge_1.19.1.jar%231100!/:23.9.7]
	at xaero.common.minimap.MinimapProcessor.onRender(MinimapProcessor.java:153) ~[Xaeros_Minimap_23.9.7_Forge_1.19.1.jar%231100!/:23.9.7]
	at xaero.common.minimap.MinimapInterfaceInstance.render(MinimapInterfaceInstance.java:53) ~[Xaeros_Minimap_23.9.7_Forge_1.19.1.jar%231100!/:23.9.7]
	at xaero.common.interfaces.render.InterfaceRenderer.renderInterfaces(InterfaceRenderer.java:71) ~[Xaeros_Minimap_23.9.7_Forge_1.19.1.jar%231100!/:23.9.7]
	at xaero.common.interfaces.render.InterfaceRenderer$1.render(InterfaceRenderer.java:144) ~[Xaeros_Minimap_23.9.7_Forge_1.19.1.jar%231100!/:23.9.7]
	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:141) ~[forge-1.19.2-43.3.5-universal.jar%231124!/:?]
	at net.minecraftforge.client.gui.overlay.ForgeGui.md4ec705$lambda$batching$0$0(ForgeGui.java:1265) ~[forge-1.19.2-43.3.5-universal.jar%231124!/:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%23121!/:?]
	at net.minecraftforge.client.gui.overlay.ForgeGui.redirect$ceh000$batching(ForgeGui.java:1259) ~[forge-1.19.2-43.3.5-universal.jar%231124!/:?]
	at net.minecraftforge.client.gui.overlay.ForgeGui.m_93030_(ForgeGui.java:136) ~[forge-1.19.2-43.3.5-universal.jar%231124!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:876) ~[client-1.19.2-20220805.130853-srg.jar%231119!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%231119!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%231119!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%231119!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%231119!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.5.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]

**Comment by AlexNijjar** [comment]
Report to Xaero. Not my issue
